import { convexTableName } from "./emit.ts";
import type { MappingNote, ParsedSchema } from "./types.ts";

function row(columns: string[]): string {
  return `| ${columns.join(" | ")} |`;
}

export function emitReport(schema: ParsedSchema, notes: MappingNote[]): string {
  const tableRows = schema.models.map((model) => {
    const modelNotes = notes.filter((note) => note.model === model.name);
    const kept = modelNotes
      .filter((note) => note.convexValidator)
      .map((note) => note.field);
    const omitted = modelNotes
      .filter((note) => !note.convexValidator)
      .map((note) => note.field);
    return row([
      model.name,
      convexTableName(model.name),
      kept.join(", ") || "-",
      omitted.join(", ") || "-",
    ]);
  });

  const fieldRows = notes.map((note) =>
    row([
      note.model,
      note.field,
      note.prismaType,
      note.convexValidator ?? "omitted",
      note.severity,
      note.message,
    ]),
  );

  const warnings = notes.filter((note) => note.severity === "warning");
  const unsupported = notes.filter(
    (note) => note.severity === "unsupported" || note.convexValidator === null,
  );

  const lines = [
    "# Prisma to Convex mapping report",
    "",
    "Generated by prisma-convex-schema.",
    "",
    "## Tables",
    "",
    row(["Prisma model", "Convex table", "Fields kept", "Fields omitted"]),
    row(["---", "---", "---", "---"]),
    ...tableRows,
    "",
    "## Field mapping",
    "",
    row(["Model", "Field", "Prisma", "Convex", "Severity", "Notes"]),
    row(["---", "---", "---", "---", "---", "---"]),
    ...fieldRows,
    "",
    "## Warnings",
    "",
  ];

  if (warnings.length === 0) {
    lines.push("None.");
  } else {
    for (const note of warnings) {
      lines.push(`- **${note.model}.${note.field}**: ${note.message}`);
    }
  }

  lines.push("", "## Unsupported / omitted", "");
  if (unsupported.length === 0) {
    lines.push("None.");
  } else {
    for (const note of unsupported) {
      lines.push(
        `- **${note.model}.${note.field}** (${note.prismaType}): ${note.message}`,
      );
    }
  }

  lines.push(
    "",
    "## Mapping reference",
    "",
    "- String -> `v.string()`",
    "- Int / Float / Decimal -> `v.number()` (Decimal warns about precision)",
    "- Boolean -> `v.boolean()`",
    "- DateTime -> ISO-8601 `v.string()`",
    "- Json -> `v.any()` with a warning",
    "- Bytes -> unsupported, omitted",
    "- Enum -> `v.union` of `v.literal` values",
    "- Optional and lists wrap the inner validator",
    "- Relations omitted and listed above",
    "",
  );

  return lines.join("\n");
}
